services:
  postgres:
    image: postgres:15-alpine
    container_name: mahjong-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mahjong_db
      POSTGRES_USER: mahjong_user
      POSTGRES_PASSWORD: mahjong_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mahjong_user -d mahjong_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mahjong-network

volumes:
  postgres_data:
    driver: local

networks:
  mahjong-network:
    driver: bridge