services:
  postgres:
    image: postgres:15-alpine
    container_name: mahjong-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: mahjong_db_dev
      POSTGRES_USER: mahjong_user
      POSTGRES_PASSWORD: mahjong_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mahjong_user -d mahjong_db_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mahjong-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: mahjong-app-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://mahjong_user:mahjong_pass@postgres:5432/mahjong_db_dev
      - NEXTAUTH_SECRET=dev-secret-key
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # Hot reload for development
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./next.config.js:/app/next.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./prisma:/app/prisma
      # Exclude node_modules for performance
      - /app/node_modules
      - /app/.next
    networks:
      - mahjong-network
    stdin_open: true
    tty: true

  redis:
    image: redis:7-alpine
    container_name: mahjong-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mahjong-network

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  mahjong-network:
    driver: bridge